book:
    title:            "Curso Symfony 2"
    author:           "Maestros del web"
    edition:          "Primera edición"
    language:         es
    publication_date: ~

    generator: { name: easybook, version: 4.4 }

    contents:
        # available content types: acknowledgement, afterword, appendix, author,
        # chapter, conclusion, cover, dedication, edition, epilogue, foreword,
        # glossary, introduction, license, lof (list of figures), lot (list of
        # tables), part, preface, prologue, title, toc (table of contents)
        - { element: cover }
        - { element: toc   }
        - { element: chapter, number: 1, content: introduccion-a-symfony-2.md }
        - { element: chapter, number: 2, content: el-proyecto-y-los-bundles.md }
        - { element: chapter, number: 3, content: creando-paginas-con-symfony-2.md }
        - { element: chapter, number: 4, content: sistema-de-routing.md }
        - { element: chapter, number: 5, content: definicion-de-rutas-con-comodines.md }
        - { element: chapter, number: 6, content: trabajando-con-el-controlador-en-symfony-2.md }
        - { element: chapter, number: 7, content: manejando-las-vistas-con-twig-en-symfony-2.md }
        - { element: chapter, number: 8, content: configurando-nuestra-base-de-datos.md }
        - { element: chapter, number: 9, content: manipulando-datos-con-doctrine.md }
        - { element: chapter, number: 10, content: creacion-de-formularios.md }
        - { element: chapter, number: 11, content: integrando-ajax.md }
        - { element: chapter, number: 12, content: instalando-bundles-de-terceros.md }
        - { element: chapter, number: 13, content: seguridad.md }

    editions:
        ebook:
            format:         epub
            highlight_code: false
            include_styles: true
            labels:         ['appendix', 'chapter']  # labels also available for: "figure", "table"
            theme:          clean
            toc:
                deep:       1
                elements:   ["appendix", "chapter", "part"]

        print:
            format:         pdf
            highlight_code: true
            include_styles: true
            isbn:           ~
            labels:         ["appendix", "chapter"]  # labels also available for: "figure", "table"
            margin:
                top:        25mm
                bottom:     25mm
                inner:      30mm
                outter:     20mm
            page_size:      A4
            theme:          clean
            toc:
                deep:       2
                elements:   ["appendix", "chapter", "part"]
            two_sided:      true

        web:
            format:         html
            highlight_code: true
            include_styles: true
            labels:         ["appendix", "chapter"]  # labels also available for: "figure", "table"
            theme:          clean
            toc:
                deep:       2
                elements:   ["appendix", "chapter"]

        website:
            extends:        web
            format:         html_chunked
